- name: FTP Deploy
  # You may pin to the exact commit or the version.
  # uses: SamKirkland/FTP-Deploy-Action@d0aa83872616587eb552bc831bb9166b3f9c5ad5
  uses: SamKirkland/FTP-Deploy-Action@4.3.0
  with:
    # ftp server
    server: ksh730506.cafe24.com
    # ftp username
    username: ksh730506
    # ftp password
    password: tjrwnsdh0209FTP!
    # Server port to connect to (read your web hosts docs)
    port: # optional
    # protocol to deploy with - ftp, ftps, or ftps-legacy
    protocol: # optional
    # Folder to upload from, must end with trailing slash /
    local-dir: # optional
    # Path to upload to on the server. Must end with trailing slash /
    server-dir: # optional
    # Path and name of the state file - this file is used to track which files have been deployed
    state-name: # optional
    # Prints which modifications will be made with current config options, but doesnt actually make any changes
    dry-run: # optional
    # Deletes ALL contents of server-dir, even items in excluded with exclude argument
    dangerous-clean-slate: # optional
    # An array of glob patterns, these files will not be included in the publish/delete process
    exclude: # optional
    # How verbose should the information be - minimal, standard, or verbose
    log-level: # optional
    # strict or loose
    security: # optional
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ksh730506.cafe24.com
        username: ksh730506
        password: ${{ tjrwnsdh0209FTP! }}